"""Deterministic 2025 Form 1040 tax computation.

This is the accuracy core of the system. The LLM never computes a tax figure;
it only gathers inputs. Every number written to the return comes from here, in
plain Python, so it is auditable and reproducible.

Methodology:
  * Standard deduction and brackets come from `tax_tables_2025` (official 2025
    values).
  * For taxable income under $100,000 the IRS requires the **Tax Table**, which
    is generated by taxing the **midpoint of each $50 income row** at the bracket
    rates and rounding to the nearest dollar. We reproduce that exact generation
    method, so our output reconciles with the published table to the dollar.
  * For taxable income of $100,000 or more the **Tax Computation Worksheet**
    applies: the continuous bracket formula on the exact amount.

Scope (documented limitation): this engine handles the W-2-only profile in the
brief — wage income, the standard deduction, and federal withholding. It does
not compute credits (EIC, CTC), itemized deductions, or non-wage income. Those
lines are left at zero, which is correct for the target taxpayer.
"""

from __future__ import annotations

from decimal import ROUND_HALF_UP, Decimal

from . import tax_tables_2025 as T
from .schemas import Form1040Result, TaxpayerInfo, W2


def _round_half_up(amount: float) -> int:
    """Round to nearest whole dollar, half up — the IRS convention."""
    return int(Decimal(str(amount)).quantize(Decimal("1"), rounding=ROUND_HALF_UP))


def _bracket_tax(taxable: float, filing_status: str) -> float:
    """Continuous progressive tax on an exact taxable-income amount."""
    brackets = T.BRACKETS[filing_status]
    tax = 0.0
    for i, (lower, rate) in enumerate(brackets):
        upper = brackets[i + 1][0] if i + 1 < len(brackets) else float("inf")
        if taxable > lower:
            taxed_in_band = min(taxable, upper) - lower
            tax += taxed_in_band * rate
        else:
            break
    return tax


def compute_tax(taxable_income: int, filing_status: str) -> tuple[int, str]:
    """Return (tax_dollars, method) for a given taxable income and filing status.

    Reproduces the IRS Tax Table for incomes below $100k and the Tax Computation
    Worksheet at or above it.
    """
    if filing_status not in T.BRACKETS:
        raise ValueError(f"Unknown filing status: {filing_status!r}")
    if taxable_income <= 0:
        return 0, "tax_table"

    if taxable_income < T.TAX_TABLE_CEILING:
        # Tax Table: tax the midpoint of the $50 row containing this income.
        row_floor = (taxable_income // 50) * 50
        midpoint = row_floor + 25
        tax = _bracket_tax(midpoint, filing_status)
        return _round_half_up(tax), "tax_table"

    # Tax Computation Worksheet: exact bracket formula, rounded.
    tax = _bracket_tax(taxable_income, filing_status)
    return _round_half_up(tax), "tax_computation_worksheet"


def compute_1040(w2: W2, info: TaxpayerInfo) -> Form1040Result:
    """Compute a complete (simple) 2025 Form 1040 from a W-2 + taxpayer info."""
    filing_status = info.filing_status

    wages = _round_half_up(w2.box1_wages)
    withholding = _round_half_up(w2.box2_federal_withholding)

    line_1a = wages
    line_1z = wages  # no other 1b-1h income in this profile
    line_9 = line_1z  # no interest/dividends/other income
    line_11_agi = line_9  # no adjustments
    std_deduction = T.STANDARD_DEDUCTION[filing_status]
    line_15_taxable = max(0, line_11_agi - std_deduction)

    tax, method = compute_tax(line_15_taxable, filing_status)

    # Child Tax Credit: $2,200 per qualifying child, capped at the tax owed
    # (simplified, non-refundable model appropriate to this profile).
    ctc = min(tax, int(info.num_dependents) * T.CHILD_TAX_CREDIT)
    line_22 = max(0, tax - ctc)
    line_24_total_tax = line_22  # no other taxes in this profile

    est = _round_half_up(info.est_payments)
    line_25d = withholding
    line_33_payments = line_25d + est

    overpaid = max(0, line_33_payments - line_24_total_tax)
    amount_owed = max(0, line_24_total_tax - line_33_payments)

    return Form1040Result(
        filing_status=filing_status,
        line_1a_wages=line_1a,
        line_1z_total_wages=line_1z,
        line_9_total_income=line_9,
        line_11_agi=line_11_agi,
        line_12_standard_deduction=std_deduction,
        line_15_taxable_income=line_15_taxable,
        line_16_tax=tax,
        line_19_ctc=ctc,
        line_22_tax_after_credits=line_22,
        line_24_total_tax=line_24_total_tax,
        line_25a_w2_withholding=withholding,
        line_25d_total_withholding=line_25d,
        line_26_est_payments=est,
        line_33_total_payments=line_33_payments,
        line_34_overpaid=overpaid,
        line_35a_refund=overpaid,
        line_37_amount_owed=amount_owed,
        tax_method=method,
    )
